### ISSUE TITLE
Header image needs a light mode variant

### ISSUE THREAD

**Issue by Ambient-Impact** [neurocracy/.github#1]
[https://github.com/kornrunner/kornrunner](https://github.com/kornrunner/kornrunner) achieves this via two links, each wrapping the light or dark mode image, with an `href` that includes `#gh-light-mode-only` and  `#gh-dark-mode-only` respectively.

```markdown
![github contribution grid snake animation](https://raw.githubusercontent.com/kornrunner/kornrunner/output/github-contribution-grid-snake-dark.svg#gh-dark-mode-only)![github contribution grid snake animation](https://raw.githubusercontent.com/kornrunner/kornrunner/output/github-contribution-grid-snake.svg#gh-light-mode-only)
```

This makes use of the following CSS that GitHub seems to provide:

```css
@media (prefers-color-scheme: light) {
  :root[data-color-mode="auto"] .entry-content [href$="#gh-dark-mode-only"],
  :root[data-color-mode="auto"] .comment-body [href$="#gh-dark-mode-only"],
  :root[data-color-mode="auto"] .readme [href$="#gh-dark-mode-only"] {
    display: none;
  }
}

@media (prefers-color-scheme: dark) {
  :root[data-color-mode="auto"] .entry-content [href$="#gh-light-mode-only"],
  :root[data-color-mode="auto"] .comment-body [href$="#gh-light-mode-only"],
  :root[data-color-mode="auto"] .readme [href$="#gh-light-mode-only"] {
    display: none;
  }
}
```
